### ISSUE TITLE
插件报错type 'Plugin' is not assignable to type 'Plugin | Plugin[]'

### ISSUE THREAD

**Issue by Content10** [OrageKK/oragekk.github.io#1]
![360截图20230420095509515](https://user-images.githubusercontent.com/19535044/233238738-edf18cfd-2f8c-460f-9342-2ddf7e69b7ec.jpg)
![360截图20230420095450389](https://user-images.githubusercontent.com/19535044/233238748-6c340de3-d0c7-4847-9935-68c2e8d96ee2.jpg)
您好，插件这种报错不知道是不是语法问题，ts不是很熟，把这几个标红的插件去调项目才能拉起来

**Comment by OrageKK** [comment]
@Content10 你是clone的我的项目吗？如果是，你需要执行`npm install`安装package.json中的这几个插件，这几个插件是官方插件，请仔细参考官方文档

**Comment by Content10** [comment]
![image](https://user-images.githubusercontent.com/19535044/233281640-53332a03-ba30-43b4-b834-986ea528067f.png)
@OrageKK 你好就是，直接clone之后就直接报错的，插件都是安装好的，在node_modules里面都可以找到，官方文档看了，没找出问题

**Comment by OrageKK** [comment]
如无错误我将关闭这个issues @Content10

**Comment by OrageKK** [comment]
@Content10 我不是专业前端，我这边是没问题的，看情况，我的本地插件没报错，引入的官方插件报类型错误，我猜测可能的问题是和你本地的环境有关系，官方已经移除了node14的支持，你检查一下你npm的版本可能过低。
我的运行环境是，`pnpm 8.3.0`,`node v18.14.0`
根据你提供的现有信息，我无法帮助你解决这个问题。
