### ISSUE TITLE
导航栏编辑[Bug]

### ISSUE THREAD

**Issue by immortalts** [OrageKK/oragekk.github.io#2]
### Checklist

- [X] I cloned this repository.
- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

右上角导航栏怎么自定义编辑图标啊

**Comment by OrageKK** [comment]
我理解你需要帮助，但这不是bug，你需要去阅读**theme-hope**的文档，
参考这里：https://theme-hope.vuejs.press/zh/guide/layout/navbar.html#%E5%B8%83%E5%B1%80%E9%85%8D%E7%BD%AE
同时我将关闭该issues
